# Generated by Django 4.1.2 on 2023-12-16 07:55

from django.db import migrations, models
import django.db.models.deletion
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week_task',
            name='week_number',
            field=models.ForeignKey(default=schedule.models.get_current_week, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='schedule.week'),
        ),
    ]
