# Generated by Django 4.2.5 on 2023-09-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=16)),
                ('number', models.CharField(max_length=64)),
                ('semester', models.CharField(max_length=64)),
            ],
        ),
    ]
